name: hospital-stay-forecast
channels:
  - conda-forge
dependencies:
  - python=3.14
  - pandas=3.0
  - pyarrow=25.0
  - requests=2.34
  - jupyterlab=4.6
  - ipykernel=7.4
  - python-dotenv=1.2
  - matplotlib=3.11
  - seaborn=0.13
  - scikit-learn=1.9
  - libblas=*=*openblas
  - pip
  - pip:
      - -e .
